spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Gkfgkx123456
    url: jdbc:mysql://gz-cynosdbmysql-grp-ib19uno3.sql.tencentcdb.com:28454/app?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml